version: '3.8'

services:
  terminal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: terminal
    ports:
      - 127.0.0.1:3001:3001
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app/src
    stdin_open: true 
    tty: true
    command: yarn dev
